### ISSUE TITLE
how to change the language?

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.darktable.Darktable#1]

**Comment by TingPing** [comment]
Applications should match how your desktop is configured but you can usually override that by setting `LANG=some_thing` in the env before launching it?

**Comment by LeandroStanger** [comment]
@nedrichards Could help

**Comment by nedrichards** [comment]
As @TingPing says, you change the language in your desktop, restart the session and launch the app, and, if the language is in the app, or a .Locale extension for the app - it should just work.

However I think there's some slightly annoying behaviour for .Locale extensions, which is that they don't get updated when you change the system language. If you didn't get all the required languages set before you install then I believe you have to manually remove and add the Locale extension, at which point, you'll magically get them to turn up. At least that's what I just reproduced for Darktable using Endless' older Flatpak 0.9.8. I know that @ramcq was looking at behaviour here (although I think it was mostly for our multi-locale images and making sure the xa bits were set properly).

**Comment by hfiguiere** [comment]
It works here.

If you still have problems, please describe precisely what you are doing.
