### ISSUE TITLE
OpenCL acceleration not available

### ISSUE THREAD

**Issue by hubslave** [flathub/org.darktable.Darktable#10]
Hello friends,

Probably I'm not first one to discover this issue, but OpenCL acceleration is not working in Darktable flatpak. "Use OpenCL" checkbox in options is greyed out. I see the same problem in Blender flatpak.

**Comment by TingPing** [comment]
Nvidia drivers?

**Comment by BellaCoola** [comment]
Yes, I'm on Nvidia laptop with Intel Graphics using PRIME setup. Could this be a problem?

**Comment by hubslave** [comment]
Yes, I'm on Nvidia laptop with Intel Graphics using PRIME setup. Could this be a problem?

**Comment by matze** [comment]
This will stay like this until https://github.com/flatpak/flatpak/issues/574 is resolved.

**Comment by hubslave** [comment]
I see that pull requests which could resolve this issue are already in place. What is the problem with merging them? AFAIK Vulkan is already implemented in nvidia driver flatpak the same way (via ICD) so what is holding back OpenCL? (Just curious)

**Comment by hubslave** [comment]
And is OpenCL on AMD and Intel already working?

**Comment by jurf** [comment]
Nope, I get only ‘not available’ on Intel.

**Comment by arigit** [comment]
AMDGPU opencl libraries: same situation. OpenCL works when the package is installed via the distro package manager, but it doesn't (opencl option greyed out) when installed via flatpak

**Comment by paperdigits** [comment]
FYI @jurf  openCL on the intel drive does not work well even with a distro package of darktable. The intel openCL driver is not good, apparently.

**Comment by paperdigits** [comment]
@matze this seems to work for me now on a system with an nVidia GTX970, KDE Neon with the nVidia driver from the Ubuntu Graphics PPA. The openCL part of the preferences now says "Very fast GPU" and the editing is quite speedy.

**Comment by matze** [comment]
Thanks for checking back!
