### ISSUE TITLE
HEIC support missing on latest flathub build

### ISSUE THREAD

**Issue by jhaiduce** [flathub/org.darktable.Darktable#102]
**Describe the bug/issue**

The latest build available on Flathub is missing HEIC support. I'm guessing it was not compiled in.

**To Reproduce**
1. Try to import from a folder containing HEIC images

or:

1. Try to open a previously imported HEIC file in Darkroom

**Expected behavior**
HEIC files should be listed in the import dialog, and should open in Darkroom

**Which commit introduced the error**

Flathub commit e373797d97926cd07de79dc754788a188ef6bd736dc7198c7b464487bf9f45de

**Platform**

* darktable version : 4.2.1, Flathub commit e373797d97926cd07de79dc754788a188ef6bd736dc7198c7b464487bf9f45de
* OS                : Linux kernel 6.1.18-200.fc37.x86_64
* Linux - Distro    : Fedora 37
* Memory            : 16 GB
* Graphics card     : Nvidia GeForce GTX 1660 SUPER
* Graphics driver   : nvidia 525.60.13
* OpenCL installed  : unknown
* OpenCL activated  : unknown
* Xorg              : 1.20.14-18.fc37.x86_64
* Desktop           : Gnome 43.3
* GTK+              : 3.24.37
* gcc               : 12.2.1
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Additional context**

HEIC support was available in Flathub release e4c1a74e092a04300c463ed8d03dbeb4de4da8dada632470533d3e41c5b59d17, (Darktable 4.2.0) and downgrading to that release restores HEIC features.

Originally reported on the Darktable github as https://github.com/darktable-org/darktable/issues/14120

**Comment by paperdigits** [comment]
I don't see a specific commit in our repo that drops support, we updated libavif.

Maybe it was dropped from one of the dependencies like the freedesktop base package?

**Comment by hfiguiere** [comment]
libheif is also at the right version.

**Comment by jhaiduce** [comment]
> If this is Fedora specific, it can't happen as HEIC as a non-free, patent encumbered format, so libheif is not available for Fedora.

To be fair I haven't tested any other distro, but my suspicion is that this is not Fedora specific since the previous flatpak build of Darktable provided HEIC support even on Fedora, which suggests that libheif was coming from the flatpak and not from a Fedora package.

**Comment by paperdigits** [comment]
Fedora having or not having an arbitrary library should not impact the flatpak, as the flatpak carries its own dependences.
