### ISSUE TITLE
Cannot import two photos via .desktop file

### ISSUE THREAD

**Issue by vascotenner** [flathub/org.darktable.Darktable#111]
My workflow is as follows: sort photos using geeqie (or nemo), and only edit specific once with darktable. 

Issue: I have to close darktable before opening the second photo. 

Reproduce: open one image via nemo on darktable (via the .desktop file). Then open a second one. Darktable complains about a lock file and a database

Expected behaviour (as I was used to before using flatpack): import the second photo in darktable.

**Comment by hfiguiere** [comment]
`org.darktable.service` needs to be exposed (`--own-name`)
