### ISSUE TITLE
Crash when thumbnail creation in Flatpak version.. DT 4.4.2

### ISSUE THREAD

**Issue by bengtfalke** [flathub/org.darktable.Darktable#112]
I am using DT 4.4.2 installed from Flatpack on Linux Mint 21.2 on the hardware below. When I open a folder with lots of photos and scroll with the mouse wheel among the thumbnails in the Lighttable view… DT suddenly crashes? Is this a known problem?
My HW:
CPU: AMD Ryzen 9 3900 (24) @ 3.100GH
GPU: NVIDIA GeForce RTX 2070 SUPER
Memory: 4773MiB / 32025MiB
SSD1: WD: WDS100T3X0C-00SJG0 size: 931.51 GiB
SSD2: Intel: SSDPEKNW020T8 size: 1.86 TiB
Linux Mint 21.2 with kernel 6.2 low latency

I will add some of the error log here..
bengt@komplett:~$ flatpak run org.darktable.Darktable -d common
0.0000 application_directory: /app/bin
0.0001 darktable.datadir: /app/share/darktable
0.0001 darktable.plugindir: /app/lib/darktable
0.0001 darktable.localedir: /app/share/locale
0.0001 darktable.configdir: /home/bengt/.var/app/org.darktable.Darktable/config/darktable
0.0001 darktable.cachedir: /home/bengt/.var/app/org.darktable.Darktable/cache/darktable
0.0001 darktable.sharedir: /app/share
0.0002 darktable.tmpdir: /tmp
0.0002 new_xdg_data_dirs: (null)
Gtk-Message: 13:42:15.568: Failed to load module “xapp-gtk3-module”
4,4737 [dt_worker_threads] using 4 worker threads
4,4951 [dt_get_sysresource_level] switched to 1 as `default’
4,4951 total mem: 32008MB
4,4951 mipmap cache: 4001MB
4,4951 available mem: 16004MB
4,4951 singlebuff: 250MB
4,4951 OpenCL tune mem: OFF
4,4951 OpenCL pinned: OFF
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: ‘very fast GPU’
[opencl_init] opencl_library: ‘default path’
[opencl_init] opencl_device_priority: ‘/!0,///!0,*’
[opencl_init] opencl_mandatory_timeout: 400
4.4967 [dt_dlopencl_init] could not find default opencl runtime library ‘libOpenCL’
4.4967 [dt_dlopencl_init] could not find default opencl runtime library ‘libOpenCL.so’
[opencl_init] opencl library ‘libOpenCL.so.1’ found on your system and loaded
[opencl_init] found 2 platforms
[opencl_init] no devices found for Mesa (vendor) - Clover (name)
[opencl_init] found 1 device

[dt_opencl_device_init]
DEVICE: 0: ‘NVIDIA GeForce RTX 2070 SUPER’
PLATFORM NAME & VENDOR: NVIDIA CUDA, NVIDIA Corporation
CANONICAL NAME: nvidiacudanvidiageforcertx2070super
DRIVER VERSION: 535.86.05
DEVICE VERSION: OpenCL 3.0 CUDA, SM_20 SUPPORT
DEVICE_TYPE: GPU
GLOBAL MEM SIZE: 7972 MB
MAX MEM ALLOC: 1993 MB
MAX IMAGE SIZE: 32768 x 32768
MAX WORK GROUP SIZE: 1024
MAX WORK ITEM DIMENSIONS: 3
MAX WORK ITEM SIZES: [ 1024 1024 64 ]
ASYNC PIXELPIPE: NO
PINNED MEMORY TRANSFER: NO
MEMORY TUNING: NO
FORCED HEADROOM: 400
AVOID ATOMICS: NO
MICRO NAP: 250
ROUNDUP WIDTH: 16
ROUNDUP HEIGHT: 16
CHECK EVENT HANDLES: 128
PERFORMANCE: 3.668
TILING ADVANTAGE: 0.000
DEFAULT DEVICE: NO
KERNEL BUILD DIRECTORY: /app/share/darktable/kernels
KERNEL DIRECTORY: /home/bengt/.var/app/org.darktable.Darktable/cache/darktable/cached_v1_kernels_for_NVIDIACUDANVIDIAGeForceRTX2070SUPER_5358605
CL COMPILER OPTION: -cl-fast-relaxed-math
KERNEL LOADING TIME: 0.0135 sec
[opencl_init] OpenCL successfully initialized. Internal numbers and names of available devices:
[opencl_init] 0 ‘NVIDIA CUDA NVIDIA GeForce RTX 2070 SUPER’
[opencl_init] FINALLY: opencl is AVAILABLE and ENABLED.
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities] image preview export thumbs preview2
[dt_opencl_update_priorities] 0 0 0 0 0
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities] image preview export thumbs preview2
[dt_opencl_update_priorities] 1 1 1 1 1
[opencl_synchronization_timeout] synchronization timeout set to 0
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities] image preview export thumbs preview2
[dt_opencl_update_priorities] 0 0 0 0 0
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities] image preview export thumbs preview2
[dt_opencl_update_priorities] 1 1 1 1 1
[opencl_synchronization_timeout] synchronization timeout set to 0
4,9114 [dt_worker_threads] using 4 worker threads
12,1902 [avif_open] failed to parse /mnt/SSD2/foton/2022/2022-01-27/3S9A8121.CR2': BMFF parsing failed 12,1904 [rawspeed_open] extensions list to ignore: cr3’
12,3596 [avif_open] failed to parse /mnt/SSD2/foton/2022/2022-01-27/3S9A8135.CR2': BMFF parsing failed 12,3597 [rawspeed_open] extensions list to ignore: cr3’
12,3692 [dt_dev_read_history_ext] temporary history deleted
12,3692 [dt_iop_reload_defaults] defaults reloaded for filmicrgb
12,3693 [dt_iop_reload_defaults] defaults reloaded for basecurve
12,3693 [dt_iop_reload_defaults] defaults reloaded for colormapping
12,3693 [dt_iop_reload_defaults] defaults reloaded for channelmixerrgb
12,3697 [dt_iop_reload_defaults] defaults reloaded for colorin
12,3698 [dt_iop_reload_defaults] defaults reloaded for crop
12,3698 [dt_iop_reload_defaults] defaults reloaded for exposure
12,3698 [dt_iop_reload_defaults] defaults reloaded for retouch
12,3698 [dt_iop_reload_defaults] defaults reloaded for clipping
12,3698 [dt_iop_reload_defaults] defaults reloaded for flip
12,3698 [dt_iop_reload_defaults] defaults reloaded for ashift
12,3698 [dt_iop_reload_defaults] defaults reloaded for cacorrectrgb
12,3705 [dt_iop_reload_defaults] defaults reloaded for lens
12,3705 [dt_iop_reload_defaults] defaults reloaded for scalepixels
12,3705 [dt_iop_reload_defaults] defaults reloaded for rotatepixels
12,3706 [dt_iop_reload_defaults] defaults reloaded for denoiseprofile
12,3706 [dt_iop_reload_defaults] defaults reloaded for demosaic
12,3706 [dt_iop_reload_defaults] defaults reloaded for rawdenoise
12,3706 [dt_iop_reload_defaults] defaults reloaded for hotpixels
12,3706 [dt_iop_reload_defaults] defaults reloaded for cacorrect
12,3706 [dt_iop_reload_defaults] defaults reloaded for highlights
12,3706 [dt_iop_reload_defaults] defaults reloaded for temperature
12,3706 [dt_iop_reload_defaults] defaults reloaded for invert
12,3706 [dt_iop_reload_defaults] defaults reloaded for rawprepare
12,3730 [dt_dev_read_history_ext] temporary history initialised with default params and presets
12,3730 [dt_dev_read_history_ext] temporary history merged with image history
12,3730 [history] successfully loaded module rawprepare from history
blendop v. 13: version ok params ok
params v. 2: version ok params ok
12,3730 [history] successfully loaded module demosaic from history
blendop v. 13: version ok params ok
params v. 4: version ok params ok
12,3730 [history] successfully loaded module colorin from history
blendop v. 13: version ok params ok
params v. 7: version ok params ok
12,3730 [history] successfully loaded module colorout from history
blendop v. 13: version ok params ok
params v. 5: version ok params ok
12,3731 [history] successfully loaded module gamma from history
blendop v. 13: version ok params ok
params v. 1: version ok params ok
12,3731 [history] successfully loaded module temperature from history
blendop v. 13: version ok params ok
params v. 3: version ok params ok
12,3731 [history] successfully loaded module highlights from history
blendop v. 13: version ok params ok
params v. 4: version ok params ok
12,3731 [history] successfully loaded module sharpen from history
blendop v. 13: version ok params ok
params v. 1: version ok params ok
12,3731 [history] successfully loaded module filmicrgb from history
blendop v. 13: version ok params ok
params v. 6: version ok params ok
12,3731 [history] successfully loaded module exposure from history
blendop v. 13: version ok params ok
params v. 6: version ok params ok
12,3731 [history] successfully loaded module flip from history
blendop v. 13: version ok params ok
params v. 2: version ok params ok
12,3731 [history] successfully loaded module sharpen from history
blendop v. 13: version ok params ok
params v. 1: version ok params ok
12,3731 [history] successfully loaded module colisa from history
blendop v. 13: version ok params ok
params v. 1: version ok params ok
12,3731 [history] successfully loaded module crop from history
blendop v. 13: version ok params ok
params v. 1: version ok params ok
12,3731 [history] successfully loaded module toneequal from history
blendop v. 13: version ok params ok
params v. 2: version ok params ok
12,3731 [history] successfully loaded module colorzones from history
blendop v. 13: version ok params ok
params v. 5: version ok params ok
12,3731 [history] successfully loaded module hazeremoval from history
blendop v. 13: version ok params ok
params v. 1: version ok params ok
12,3731 [history] successfully loaded module denoiseprofile from history
blendop v. 13: version ok params ok
params v. 11: version ok params ok
12,3731 [history] successfully loaded module colorzones from history
blendop v. 13: version ok params ok
params v. 5: version ok params ok
12,3731 [history] successfully loaded module colisa from history
blendop v. 13: version ok params ok
params v. 1: version ok params ok
12,3776 [pixelpipe] [thumbnail] synch all modules with defaults_params
12,3776 [iop_validate_params] temperature' failed for type "float", field: g2 12,3776 [iop_validate_params] temperature’ failed for type “dt_iop_temperature_params_t”
12,4120 [iop_validate_params] borders' failed for type "float", field: aspect 12,4120 [iop_validate_params] borders’ failed for type “dt_iop_borders_params_t”
12,4120 [pixelpipe] [thumbnail] synch all modules with history
12,4120 [committed params] [thumbnail] rawprepare piece hash 13545888354904502509,
12,4120 [committed params] [thumbnail] demosaic piece hash 12713709861679059410,
12,4121 [committed params] [thumbnail] colorin piece hash 8458784419482823018,
12,4168 [committed params] [thumbnail] colorout piece hash 10257528088492143908,
12,4169 [committed params] [thumbnail] gamma piece hash 7567884774754821,
12,4169 [committed params] [thumbnail] temperature piece hash 2842170463207298814,
12,4169 [committed params] [thumbnail] highlights piece hash 573611052330575869,
12,4169 [committed params] [thumbnail] sharpen piece hash 5131174322306221296,
12,4169 [committed params] [thumbnail] filmicrgb piece hash 16197511981616913186,
12,4169 [committed params] [thumbnail] exposure piece hash 8484767493419708776,
12,4169 [committed params] [thumbnail] flip piece hash 0,
12,4169 [committed params] [thumbnail] sharpen piece hash 5131174322306221296,
12,4174 [committed params] [thumbnail] colisa piece hash 11124742604436387888,
12,4174 [committed params] [thumbnail] crop piece hash 2104806362480157189,
12,4221 [committed params] [thumbnail] toneequal piece hash 17457874357210582453,
12,4257 [committed params] [thumbnail] colorzones piece hash 0,
12,4257 [committed params] [thumbnail] hazeremoval piece hash 9701723546632932278,
12,4261 [committed params] [thumbnail] denoiseprofile piece hash 658185497937747507,
12,4293 [committed params] [thumbnail] colorzones piece hash 7836307137121302961,
12,4296 [committed params] [thumbnail] colisa piece hash 11124742604436387888,
12,4296 [dt_imageio_export_with_flags] 12,4296
12,4296 rawprepare 12,4296 temperature 12,4296 highlights 12,4296 demosaic 12,4296 denoiseprofile 12,4296 hazeremoval 12,4296 exposure 12,4296 toneequal 12,4296 crop 12,4296 colorin 12,4296 sharpen 12,4296 filmicrgb 12,4296 colisa 12,4296 colorzones 12,4296 colorout 12,4296 gamma 12,4296 (16)
12,4297 [dt_imageio_export] [thumbnail] imgid 48478, 3729x2956 → 567x450 (scale 0,152233). upscale=no, hq=no
12,4297 [pixelpipe starting CL] [thumbnail] ( 0/ 0) 567x 450 scale=0,1522 → ( 0/ 0) 567x 450 scale=0,1522
12,4297 [dt_opencl_check_tuning] use 5175MB (tunemem=OFF, pinning=OFF) on device NVIDIA CUDA NVIDIA GeForce RTX 2070 SUPER' id=0 12,4297 [modify roi IN] [thumbnail] crop ( 169/ 61) 567x 450 scale=0,1522 --> ( 0/ 0) 567x 450 scale=0,1522 12,4297 [modify roi IN] [thumbnail] demosaic (1110/ 400) 3724x2956 scale=1,0000 --> ( 169/ 61) 567x 450 scale=0,1522 12,4297 [modify roi IN] [thumbnail] rawprepare (1110/ 400) 3796x2994 scale=1,0000 --> (1110/ 400) 3724x2956 scale=1,0000 12,4297 [pixelpipe data: 1:1 copied] [thumbnail] (1110/ 400) 3796x2994 scale=1,0000 --> (1110/ 400) 3796x2994 scale=1,0000 bpp=2 12,4363 [pixelpipe_process_CL] [thumbnail] rawprepare (1110/ 400) 3796x2994 scale=1,0000 --> (1110/ 400) 3724x2956 scale=1,0000 IOP_CS_RAW 12,4375 [pixelpipe_process_CL] [thumbnail] temperature (1110/ 400) 3724x2956 scale=1,0000 --> (1110/ 400) 3724x2956 scale=1,0000 IOP_CS_RAW 12,4385 [pixelpipe_process_CL] [thumbnail] highlights (1110/ 400) 3724x2956 scale=1,0000 --> (1110/ 400) 3724x2956 scale=1,0000 IOP_CS_RAW 12,4396 [pixelpipe_process_CL] [thumbnail] demosaic (1110/ 400) 3724x2956 scale=1,0000 --> ( 169/ 61) 567x 450 scale=0,1522 IOP_CS_RAW -> IOP_CS_RGB 12,4407 [pixelpipe_process_CL] [thumbnail] denoiseprofile ( 169/ 61) 567x 450 scale=0,1522 --> ( 169/ 61) 567x 450 scale=0,1522 IOP_CS_RGB 12,4459 [pixelpipe_process_CL] [thumbnail] hazeremoval ( 169/ 61) 567x 450 scale=0,1522 --> ( 169/ 61) 567x 450 scale=0,1522 IOP_CS_RGB 12,4602 [pixelpipe_process_CL] [thumbnail] exposure ( 169/ 61) 567x 450 scale=0,1522 --> ( 169/ 61) 567x 450 scale=0,1522 IOP_CS_RGB 12,4643 [pixelpipe_process_on_CPU] [thumbnail] toneequal ( 169/ 61) 567x 450 scale=0,1522 --> ( 169/ 61) 567x 450 scale=0,1522 IOP_CS_RGB 12,4687 [pixelpipe_process_CL] [thumbnail] crop ( 169/ 61) 567x 450 scale=0,1522 --> ( 0/ 0) 567x 450 scale=0,1522 IOP_CS_RGB 12,4693 [pixelpipe_process_CL] [thumbnail] colorin ( 0/ 0) 567x 450 scale=0,1522 --> ( 0/ 0) 567x 450 scale=0,1522 IOP_CS_RGB -> IOP_CS_LAB 12,4693 [matrix conversion on GPU] [thumbnail] colorin ( 0/ 0) 567x 450 scale=0,1522 --> ( 0/ 0) 567x 450 scale=0,1522 standard color matrix’
12,4706 [pixelpipe_process_CL] [thumbnail] sharpen ( 0/ 0) 567x 450 scale=0,1522 → ( 0/ 0) 567x 450 scale=0,1522 IOP_CS_LAB
12,4716 [transform colorspace CL] [thumbnail] filmicrgb ( 0/ 0) 567x 450 scale=0,1522 → ( 0/ 0) 567x 450 scale=0,1522 IOP_CS_LAB → IOP_CS_RGB
12,4737 [pixelpipe_process_CL] [thumbnail] filmicrgb ( 0/ 0) 567x 450 scale=0,1522 → ( 0/ 0) 567x 450 scale=0,1522 IOP_CS_RGB
12,4761 [transform colorspace CL] [thumbnail] colisa ( 0/ 0) 567x 450 scale=0,1522 → ( 0/ 0) 567x 450 scale=0,1522 IOP_CS_RGB → IOP_CS_LAB
12,4782 [pixelpipe_process_CL] [thumbnail] colisa ( 0/ 0) 567x 450 scale=0,1522 → ( 0/ 0) 567x 450 scale=0,1522 IOP_CS_LAB
12,4794 [pixelpipe_process_CL] [thumbnail] colorzones ( 0/ 0) 567x 450 scale=0,1522 → ( 0/ 0) 567x 450 scale=0,1522 IOP_CS_LAB
12,4804 [pixelpipe_process_CL] [thumbnail] colorout ( 0/ 0) 567x 450 scale=0,1522 → ( 0/ 0) 567x 450 scale=0,1522 IOP_CS_LAB → IOP_CS_RGB
12,4825 [pixelpipe_process_on_CPU] [thumbnail] gamma ( 0/ 0) 567x 450 scale=0,1522 → ( 0/ 0) 567x 450 scale=0,1522 IOP_CS_RGB
12,4830 [cache report] [thumbnail] 2 lines (important=0, used=0, invalid=0). Used 630MB, limit=0MB. hits/run=0,00, hits/test=0,000
12,4830 [pixelpipe finished] [thumbnail] ( 0/ 0) 567x 450 scale=0,1522 → ( 0/ 0) 567x 450 scale=0,1522

12,5625 [dt_dev_read_history_ext] temporary history deleted
12,5625 [dt_iop_reload_defaults] defaults reloaded for filmicrgb
12,5626 [dt_iop_reload_defaults] defaults reloaded for basecurve
12,5626 [dt_iop_reload_defaults] defaults reloaded for colormapping
12,5626 [dt_iop_reload_defaults] defaults reloaded for channelmixerrgb
12,5629 [dt_iop_reload_defaults] defaults reloaded for colorin
12,5629 [dt_iop_reload_defaults] defaults reloaded for crop
12,5629 [dt_iop_reload_defaults] defaults reloaded for exposure
12,5629 [dt_iop_reload_defaults] defaults reloaded for retouch
12,5629 [dt_iop_reload_defaults] defaults reloaded for clipping
12,5629 [dt_iop_reload_defaults] defaults reloaded for flip
12,5629 [dt_iop_reload_defaults] defaults reloaded for ashift
12,5629 [dt_iop_reload_defaults] defaults reloaded for cacorrectrgb
12,5636 [dt_iop_reload_defaults] defaults reloaded for lens
12,5636 [dt_iop_reload_defaults] defaults reloaded for scalepixels
12,5636 [dt_iop_reload_defaults] defaults reloaded for rotatepixels
12,5637 [dt_iop_reload_defaults] defaults reloaded for denoiseprofile
12,5637 [dt_iop_reload_defaults] defaults reloaded for demosaic
12,5637 [dt_iop_reload_defaults] defaults reloaded for rawdenoise
12,5637 [dt_iop_reload_defaults] defaults reloaded for hotpixels
12,5637 [dt_iop_reload_defaults] defaults reloaded for cacorrect
12,5637 [dt_iop_reload_defaults] defaults reloaded for highlights
12,5637 [dt_iop_reload_defaults] defaults reloaded for temperature
12,5637 [dt_iop_reload_defaults] defaults reloaded for invert
12,5637 [dt_iop_reload_defaults] defaults reloaded for rawprepare
12,5660 [dt_dev_read_history_ext] temporary history initialised with default params and presets
12,5660 [dt_dev_read_history_ext] temporary history merged with image history
12,5661 [history] successfully loaded module rawprepare from history
		blendop v. 13:	version ok	params ok
		params v. 2:	version ok	params ok
12,5661 [history] successfully loaded module demosaic from history
		blendop v. 13:	version ok	params ok
		params v. 4:	version ok	params ok
12,5661 [history] successfully loaded module colorin from history
		blendop v. 13:	version ok	params ok
		params v. 7:	version ok	params ok
12,5661 [history] successfully loaded module colorout from history
		blendop v. 13:	version ok	params ok
		params v. 5:	version ok	params ok
12,5661 [history] successfully loaded module gamma from history
		blendop v. 13:	version ok	params ok
		params v. 1:	version ok	params ok
12,5661 [history] successfully loaded module temperature from history
		blendop v. 13:	version ok	params ok
		params v. 3:	version ok	params ok
12,5661 [history] successfully loaded module highlights from history
		blendop v. 13:	version ok	params ok
		params v. 4:	version ok	params ok
12,5661 [history] successfully loaded module filmicrgb from history
		blendop v. 13:	version ok	params ok
		params v. 6:	version ok	params ok
12,5661 [history] successfully loaded module exposure from history
		blendop v. 13:	version ok	params ok
		params v. 6:	version ok	params ok
12,5661 [history] successfully loaded module flip from history
		blendop v. 13:	version ok	params ok
		params v. 2:	version ok	params ok
12,5662 [history] successfully loaded module crop from history
		blendop v. 13:	version ok	params ok
		params v. 1:	version ok	params ok
12,5691 [pixelpipe] [thumbnail] synch all modules with defaults_params
12,5691 [iop_validate_params] `temperature' failed for type "float", field: g2
12,5691 [iop_validate_params] `temperature' failed for type "dt_iop_temperature_params_t"
12,6010 [iop_validate_params] `borders' failed for type "float", field: aspect
12,6010 [iop_validate_params] `borders' failed for type "dt_iop_borders_params_t"
12,6010 [pixelpipe] [thumbnail] synch all modules with history
12,6010 [committed params]           [thumbnail]    rawprepare              piece hash    923521586991769965, 
12,6010 [committed params]           [thumbnail]    demosaic                piece hash  12713709861679059410, 
12,6010 [committed params]           [thumbnail]    colorin                 piece hash   8458784419482823018, 
12,6055 [committed params]           [thumbnail]    colorout                piece hash  10257528088492143908, 
12,6056 [committed params]           [thumbnail]    gamma                   piece hash      7567884774754821, 
12,6056 [committed params]           [thumbnail]    temperature             piece hash   2842170463207298814, 
12,6056 [committed params]           [thumbnail]    highlights              piece hash    573611052330575869, 
12,6056 [committed params]           [thumbnail]    filmicrgb               piece hash  16197511981616913186, 
12,6056 [committed params]           [thumbnail]    exposure                piece hash   8484767493419708776, 
12,6056 [committed params]           [thumbnail]    flip                    piece hash                     0, 
12,6056 [committed params]           [thumbnail]    crop                    piece hash   2104806362480157189, 
12,6056 [dt_imageio_export_with_flags]     12,6056 
12,6056  rawprepare    12,6056  temperature    12,6056  highlights    12,6056  demosaic    12,6056  exposure    12,6056  crop    12,6056  colorin    12,6056  filmicrgb    12,6056  colorout    12,6056  gamma    12,6056  (10)
12,6056 [dt_imageio_export] [thumbnail] imgid 48481, 2918x2214 --> 593x450 (scale 0,203252). upscale=no, hq=no
12,6056 [pixelpipe starting CL]      [thumbnail]                           (   0/   0)  593x 450 scale=0,2033 --> (   0/   0)  593x 450 scale=0,2033 
12,6057 [modify roi IN]              [thumbnail]    crop                   ( 338/ 160)  593x 450 scale=0,2033 --> (   0/   0)  593x 450 scale=0,2033 
12,6057 [modify roi IN]              [thumbnail]    demosaic               (1662/ 786) 2917x2214 scale=1,0000 --> ( 338/ 160)  593x 450 scale=0,2033 
12,6057 [modify roi IN]              [thumbnail]    highlights             (   0/   0) 5496x3670 scale=1,0000 --> (1662/ 786) 2917x2214 scale=1,0000 
12,6057 [modify roi IN]              [thumbnail]    rawprepare             (   0/   0) 5568x3708 scale=1,0000 --> (   0/   0) 5496x3670 scale=1,0000 
12,6057 [pixelpipe data: full]       [thumbnail]                           (   0/   0) 5568x3708 scale=1,0000 --> (   0/   0) 5568x3708 scale=1,0000 
12,6126 [pixelpipe_process_CL]       [thumbnail]    rawprepare             (   0/   0) 5568x3708 scale=1,0000 --> (   0/   0) 5496x3670 scale=1,0000 IOP_CS_RAW
12,6139 [pixelpipe_process_CL]       [thumbnail]    temperature            (   0/   0) 5496x3670 scale=1,0000 --> (   0/   0) 5496x3670 scale=1,0000 IOP_CS_RAW
12,6155 [pixelpipe_process_CL]       [thumbnail]    highlights             (   0/   0) 5496x3670 scale=1,0000 --> (1662/ 786) 2917x2214 scale=1,0000 IOP_CS_RAW
12,6202 [pixelpipe_process_CL]       [thumbnail]    demosaic               (1662/ 786) 2917x2214 scale=1,0000 --> ( 338/ 160)  593x 450 scale=0,2033 IOP_CS_RAW -> IOP_CS_RGB
12,6213 [pixelpipe_process_CL]       [thumbnail]    exposure               ( 338/ 160)  593x 450 scale=0,2033 --> ( 338/ 160)  593x 450 scale=0,2033 IOP_CS_RGB
12,6223 [pixelpipe_process_CL]       [thumbnail]    crop                   ( 338/ 160)  593x 450 scale=0,2033 --> (   0/   0)  593x 450 scale=0,2033 IOP_CS_RGB
12,6228 [pixelpipe_process_CL]       [thumbnail]    colorin                (   0/   0)  593x 450 scale=0,2033 --> (   0/   0)  593x 450 scale=0,2033 IOP_CS_RGB -> IOP_CS_LAB
12,6228 [matrix conversion on GPU]   [thumbnail]    colorin                (   0/   0)  593x 450 scale=0,2033 --> (   0/   0)  593x 450 scale=0,2033 `standard color matrix'
12,6240 [transform colorspace CL]    [thumbnail]    filmicrgb              (   0/   0)  593x 450 scale=0,2033 --> (   0/   0)  593x 450 scale=0,2033 IOP_CS_LAB -> IOP_CS_RGB
12,6258 [pixelpipe_process_CL]       [thumbnail]    filmicrgb              (   0/   0)  593x 450 scale=0,2033 --> (   0/   0)  593x 450 scale=0,2033 IOP_CS_RGB
12,6278 [transform colorspace CL]    [thumbnail]    colorout               (   0/   0)  593x 450 scale=0,2033 --> (   0/   0)  593x 450 scale=0,2033 IOP_CS_RGB -> IOP_CS_LAB
12,6293 [pixelpipe_process_CL]       [thumbnail]    colorout               (   0/   0)  593x 450 scale=0,2033 --> (   0/   0)  593x 450 scale=0,2033 IOP_CS_LAB -> IOP_CS_RGB
12,6315 [pixelpipe_process_on_CPU]   [thumbnail]    gamma                  (   0/   0)  593x 450 scale=0,2033 --> (   0/   0)  593x 450 scale=0,2033 IOP_CS_RGB
12,6321 [cache report]               [thumbnail]                            2 lines (important=0, used=0, invalid=0). Used 630MB, limit=0MB. hits/run=0,00, hits/test=0,000
12,6321 [pixelpipe finished]         [thumbnail]                           (   0/   0)  593x 450 scale=0,2033 --> (   0/   0)  593x 450 scale=0,2033 

12,9909 [avif_open] failed to parse `/mnt/SSD2/foton/2022/2022-01-29/3S9A8194.CR2': BMFF parsing failed
12,9910 [rawspeed_open] extensions list to ignore: `cr3'
13,0032 [avif_open] failed to parse `/mnt/SSD2/foton/2022/2022-01-29/GOPR0637.GPR': BMFF parsing failed
13,0033 [rawspeed_open] extensions list to ignore: `cr3'

/usr/include/c++/12.2.0/optional:477: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = rawspeed::PrefixCodeLUTDecoder<rawspeed::VC5CodeTag, rawspeed::PrefixCodeVectorDecoderrawspeed::VC5CodeTag >; _Dp = std::_Optional_base<rawspeed::PrefixCodeLUTDecoder<rawspeed::VC5CodeTag, rawspeed::PrefixCodeVectorDecoderrawspeed::VC5CodeTag >, false, false>]: Assertion ‘this->_M_is_engaged()’ failed.

I ended up uninstalling the Flatpak version and installed the Git building service darktable_4.5.0~git299.7c86465b-1+10432.1_amd64(2).deb… and then all was fine.

**Comment by paperdigits** [comment]
You have corrupted files. Get rid of them and things will be fine.

**Comment by bengtfalke** [comment]
No that is not so! I sent some file to a friend and he could read them without any issues. I could also view them all from a Windows installtion of DT on the same machine... that suggetst to me that the files are fine. I then uninstalled the Flatpak version of DT and installed from the GIT building service. I importad the same photos (52000 of them) and all works fine. The problem is probably Flathub oriented....

**Comment by paperdigits** [comment]
Please provide samples of problematic images.

**Comment by bengtfalke** [comment]
This one made DT crash... but just opening a folder with it in crashed DT... but that was just the Flatpak version... now all is fine. The forum don't support raw files in the CR2 format (Canon)... that is odd

**Comment by victoryforce** [comment]
> Please provide samples of problematic images.

The sample is provided in https://github.com/darktable-org/darktable/issues/15022#issuecomment-1673282963

I can confirm that importing this file alone causes flatpak dt 4.4.2 to crash. At the same time, the native builds of dt 4.4.2 (I checked the Windows, macOS and Ubuntu builds myself) do not have any problems with this file.

**Comment by Nine-H** [comment]
I'm having the same issue on the flatpak version but also the manjaro native package, the app works fine on a fresh install or after removing the cache and config directories but when I try to import any photos I get the following assertion error:

```
     2.0346 [avif_open] failed to parse `/home/nine/Pictures/teahouse reef raws/GOPR0340.GPR': BMFF parsing failed
     2.0347 [rawspeed_open] extensions list to ignore: `cr3'
/usr/include/c++/13.2.1/optional:477: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = rawspeed::PrefixCodeLUTDecoder<rawspeed::VC5CodeTag, rawspeed::PrefixCodeVectorDecoder<rawspeed::VC5CodeTag> >; _Dp = std::_Optional_base<rawspeed::PrefixCodeLUTDecoder<rawspeed::VC5CodeTag, rawspeed::PrefixCodeVectorDecoder<rawspeed::VC5CodeTag> >, false, false>]: Assertion 'this->_M_is_engaged()' failed.
zsh: IOT instruction (core dumped)  darktable -d common
```

And it crashes the app over and over again until I wipe it. with or without OpenCL enabled with the commandline switch.

I've also verified that my photos work perfectly in the windows version of darktable, but not on the same machine.

**Comment by paperdigits** [comment]
If you move the file GOPR0340.GPR out of the import, does it succeed? The file might be corrupted.

**Comment by hfiguiere** [comment]
The reason why it happen inside of flatpak is that flatpak is built with CXX_ASSERTIONS enabled. Which catch a lot of programming bugs. This is based on the crash message.

**Comment by hfiguiere** [comment]
Upstream comment. It's an upstream bug. There is absolutely no doubt.

https://github.com/darktable-org/darktable/issues/15022#issuecomment-1893032868
