### ISSUE TITLE
Verifying the package as an official one

### ISSUE THREAD

**Issue by zefr0x** [flathub/org.darktable.Darktable#115]
Since this flatpak package is mentioned in darktable's official website, in https://www.darktable.org/install/. It would be a great thing if it is verified in flathub.

Read more: https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by paperdigits** [comment]
Probably not going to happen, the official stance of the project, especially for *nix, is that they distribute source code only.

I see that I obliterated the "3rd party" header in one of my website refactors, I should probably add it back.

**Comment by zefr0x** [comment]
I understand this, but flatpak is a universal package that represents the project in Linux, so they might reconsider this idea and make an exception.

**Comment by paperdigits** [comment]
The problem is that if you endorse one, you have to endorse them all, since snap and appimage and statically compiled binaries are also universal package formats on Linux.

We have been over this several times before, and the answer has always been the same.
