### ISSUE TITLE
Missing AVIF export in darktable 4.6.0

### ISSUE THREAD

**Issue by kadykov** [flathub/org.darktable.Darktable#118]
### Describe the bug

In the export module the export in the AVIF format is missing.
In darktable 4.4.2 this option was present and it was working great.

### Steps to reproduce

In darkroom or in lighttable open export module and try to find AVIF format export.

### Expected behavior

AVIF format export should be available

### Logfile | Screenshot | Screencast

![Screenshot from 2024-01-04 15-15-30](https://github.com/darktable-org/darktable/assets/62546709/0f558365-33c7-43e3-a802-3eed53d55857)

### Where did you obtain darktable from?

Flatpak from flathub

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Fedora Silverblue 39

### Describe your system?

All the images are in a NFS storage.

#### System Details Report
---

##### Report details
- **Date generated:**                              2024-01-04 15:21:19

##### Hardware Information:
- **Hardware Model:**                              Lenovo ThinkPad T14 Gen 1
- **Memory:**                                      40,0 GiB
- **Processor:**                                   AMD Ryzen™ 5 PRO 4650U with Radeon™ Graphics × 12
- **Graphics:**                                    AMD Radeon™ Graphics
- **Disk Capacity:**                               256,1 GB

##### Software Information:
- **Firmware Version:**                            R1BET77W(1.46 )
- **OS Name:**                                     Fedora Linux 39.20240103.0 (Silverblue)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.2
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.8-200.fc39.x86_64

This issue was also posted in [general darktable issues](https://github.com/darktable-org/darktable/issues/16026)

**Comment by hfiguiere** [comment]
it's probably related to https://github.com/flathub/org.darktable.Darktable/pull/117#issuecomment-1870760390

**Comment by kmilos** [comment]
> it's probably related to https://github.com/flathub/org.darktable.Darktable/pull/117#issuecomment-1870760390

Don't think so.

[Please keep up w/ the release notes when packaging - the "Changed Dependencies" section](https://www.darktable.org/2023/12/darktable-4.6.0-released/) does mention libavif requirement was bumped to at least 0.9.2.

**Comment by hfiguiere** [comment]
the build system didn't check the specific version. It's 0.9.1...

**Comment by kmilos** [comment]
The build system could indeed be improved to fail hard if the requested feature is not exactly satisfied (WIP: https://github.com/darktable-org/darktable/issues/15803)...

Still, the release notes (and the [list of dependencies on the project README](https://github.com/darktable-org/darktable?tab=readme-ov-file#dependencies)) should be clear and helpful enough for packagers to follow.

**Comment by hfiguiere** [comment]
> does mention libavif requirement was bumped to at least 0.9.2.

Except that this doesn't fix it. So there.

**Comment by kmilos** [comment]
> Except that this doesn't fix it.

Ah... Turns out the libavif 0.9.2 tag/tarball was still reporting itself as 0.9.1! https://github.com/AOMediaCodec/libavif/blob/v0.9.2/CMakeLists.txt#L10

I might as well bump the docs/cmake to 0.9.3 then...
