### ISSUE TITLE
RustiCL not working

### ISSUE THREAD

**Issue by Eckoa** [flathub/org.darktable.Darktable#122]
Seeing as the current Flatpak Mesa looks to be built with RustiCL support https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/extensions/mesa/mesa.yml?ref_type=heads i figured i would give it a try. 

Unfortunately there doesnt seem to be any way to get this flatpak to recognize it being there. Using RUSTICL_ENABLE=radeonsi or OCL_ICD_VENDORS environment variables does nothing to help the situation. In theory the inclusion of RustiCL should allow at least experimental OpenCL for AMD users. 

Im not very familiar with how exactly flatpak runtimes all work but maybe the org.gnome.Sdk used here doesnt expose RustiCL? I would think the default mesa having it would be enough.

**Comment by paperdigits** [comment]
I believe you need the same mesa version installed on your system, I might be wrong tho.

**Comment by Eckoa** [comment]
I wouldnt think you would need both Mesa to match, afaik the flatpak mesa is completely separate from system mesa and shouldnt require either to match as flatpak provides  everything itself in this case

**Comment by paperdigits** [comment]
What does `darktable -d opencl` say?

**Comment by Eckoa** [comment]
After a little more testing Ive found that even though RustiCL is built in even org.freedesktop.Platform.ClInfo cant be made to see it, i dont think this is something that cane be remedied here but might be something runtime related.

**Comment by Eckoa** [comment]
> What does `darktable -d opencl` say?
> […](#)
> On February 25, 2024 11:31:08 AM PST, Echoa ***@***.***> wrote: I wouldnt think you would need both Mesa to match, afaik the flatpak mesa is completely separate from system mesa and shouldnt require either to match as flatpak provides everything itself in this case -- Reply to this email directly or view it on GitHub: [#122 (comment)](https://github.com/flathub/org.darktable.Darktable/issues/122#issuecomment-1963037744) You are receiving this because you commented. Message ID: ***@***.***>

flatpak run --env=RUSTICL_ENABLE=radeonsi org.darktable.Darktable -d opencl 

reports 0 platforms detected when in "theory" it should see my rx6800 with opencl 3.0 through rusticl but i tried with flatpak clinfo and that doesnt work either so i think ill close this as i dont think anything can be done here
