### ISSUE TITLE
Export JPEG seems Broken on Flatpak 4.6.1 Debian 12.5

### ISSUE THREAD

**Issue by dorpauli** [flathub/org.darktable.Darktable#123]
Since I already opened an issue on Darktable's repo, I'll just copy it here. Please note the discussion there. https://github.com/darktable-org/darktable/issues/16979

# Describe the bug

If i want to export an image as jpeg (8-bit), i'm not able to set any options for that format. Then when i export the image, it is exported as whatever was selected before jpeg, for example png, tiff or webp. This is the case in lighttable and darkroom. I have installed Darktable via Flatpak and it's on version 4.6.1. I am on Debian 12.5.
![image](https://github.com/flathub/org.darktable.Darktable/assets/70518303/19fd59d4-fedd-4c6a-877a-11d5c50f2c5b)
# Steps to reproduce

1.Start Darktable
2. Select any Image
3.Try to export as jpeg if sth. else was selected before

# Expected behavior

I should make settings like jpeg compression and so on. And then it should export as jpeg.
# Logfile | Screenshot | Screencast

No response
# Commit

No response
# Where did you obtain darktable from?

flatpak
# darktable version

darktable developers org.darktable.Darktable 4.6.1 stable system
# What OS are you using?

Linux
# What is the version of your OS?

Debian 12.5
# Describe your system?

Its a thinkpad x1 extreme gen2 with 32gb ram and an core i7 and an nvidia graphics card. I run on Gnome Desktop with X11 instead of new wayland.
# Are you using OpenCL GPU in darktable?

No
# If yes, what is the GPU card and driver?

OpenCL is not selectable in settings
# Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

No response

**Comment by paperdigits** [comment]
Hi, can you start darktable with the option -d all, replicate the issue, then provide the output here please?

**Comment by dorpauli** [comment]
> Hi, can you start darktable with the option -d all, replicate the issue, then provide the output here please?
> […](#)
> On June 19, 2024 10:57:01 AM PDT, "Paul F." ***@***.***> wrote: Since I already opened an issue on Darktable's repo, I'll just copy it here. Please note the discussion there. [darktable-org/darktable#16979](https://github.com/darktable-org/darktable/issues/16979) # Describe the bug If i want to export an image as jpeg (8-bit), i'm not able to set any options for that format. Then when i export the image, it is exported as whatever was selected before jpeg, for example png, tiff or webp. This is the case in lighttable and darkroom. I have installed Darktable via Flatpak and it's on version 4.6.1. I am on Debian 12.5. ![image](https://github.com/flathub/org.darktable.Darktable/assets/70518303/19fd59d4-fedd-4c6a-877a-11d5c50f2c5b) # Steps to reproduce 1.Start Darktable 2. Select any Image 3.Try to export as jpeg if sth. else was selected before # Expected behavior I should make settings like jpeg compression and so on. And then it should export as jpeg. # Logfile | Screenshot | Screencast No response # Commit No response # Where did you obtain darktable from? flatpak # darktable version darktable developers org.darktable.Darktable 4.6.1 stable system # What OS are you using? Linux # What is the version of your OS? Debian 12.5 # Describe your system? Its a thinkpad x1 extreme gen2 with 32gb ram and an core i7 and an nvidia graphics card. I run on Gnome Desktop with X11 instead of new wayland. # Are you using OpenCL GPU in darktable? No # If yes, what is the GPU card and driver? OpenCL is not selectable in settings # Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip No response -- Reply to this email directly or view it on GitHub: #123 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

It seems that I am too late. I was going to send you the logs, but with the latest update the problem has disappeared. Thanks anyway.
