### ISSUE TITLE
4.8.0 broken (opcode close: Corrupted file object;)

### ISSUE THREAD

**Issue by mikae1** [flathub/org.darktable.Darktable#125]
Was happy to see that 4.8.0 just arrived. I’m all Flatpaks for GUI apps. Just did `flatpak upgrade` and the only app that failed upgrading was darktable. I got this message:
`Error: While pulling app/org.darktable.Darktable/x86_64/stable from remote flathub: opcode close: Corrupted file object; checksum expected='32a1a3776bb1fbf9b903cdc0c364a89d9caf368e0fa3b1297088dad464324be3' actual='bc15f3b624d65290716ab81daaabffb3d69954927d624e6758eb7c2ecbc681c9'`

**Comment by hfiguiere** [comment]
update worked fine here. Nothing we can do anyway.

**Comment by paperdigits** [comment]
Please try the update again (rollback first if necessary) and if this still happens check your ram, check your disk, or try switching to a different internet at a cafe or something.

**Comment by paperdigits** [comment]
This seems like a network or local disk issue, please reopen this issue if necessary.
