### ISSUE TITLE
Darktable is not using all cpu cores when exporting, despite "Important" resource allocation parameter

### ISSUE THREAD

**Issue by viba1** [flathub/org.darktable.Darktable#130]
**Description:**

When exporting photos from Darktable running in a Flatpak environment, it appears that only one CPU core is being utilized, even though the "Darktable Resources" setting is set to "Important". 

This behavior seems inconsistent with the expected resource allocation and can lead to significantly longer export times. 

**Steps to Reproduce:**

1. Install Darktable via Flatpak: `flatpak install flathub org.darktable.Darktable`
2. Open Darktable and adjust the "Darktable Resources" setting to "Important".
3. Export a photo or batch of photos using any desired settings.
4. Observe CPU utilization during the export process using a system monitoring tool like `top` or `htop`.

**Expected Behavior:**

Multiple CPU cores should be utilized during the export process, especially with the "Important" resource allocation setting. This would result in faster export times and efficient use of available 
hardware resources.

**Actual Behavior:**

Only one CPU core is being actively used during the export process, regardless of the "Darktable Resources" setting. 

**Environment:**

* Debian Version: 12
* Darktable Version: 4.8.1
* Flatpak Version: 1.14.10

Does anyone have any ideas?
Please let me know if you require any further information or logs to assist in debugging my issue.
![Capture d’écran du 2024-09-28 22-55-50](https://github.com/user-attachments/assets/e55cbe85-fc6c-42d8-a9b7-2cda4aa3bda9)

**Comment by paperdigits** [comment]
Exporting to what format? Not all underlying libraries are multi threaded and for some they don't need to hammer your CPU (especially if you have a GPU).

And do you think this is a problem explicitly with the flatpak? Have you tested against the AppImage?

**Comment by viba1** [comment]
@paperdigits : thanks for your quick answer and your analysis.
I just have test using different export formats and it seems that the problem mainly occurs with .PNG format.
So I have also test it with a native darktable and gimp with the same behaviour.
Exports to .JPEG or .TIFF formats are hugly much faster due to the parallelization.

This ticket could be closed. Sorry for the question.
