### ISSUE TITLE
Corrupting images

### ISSUE THREAD

**Issue by ChristopherRogers1991** [flathub/org.darktable.Darktable#133]
The latest version, based on Gnome 47 runtime, is producing errors such as the following:

```
   353.5860 [libraw_open] extensions whitelist: `cr3 rw2'                                                                                                     
   353.5877 [libraw_open] extensions whitelist: `cr3 rw2'                                                                                                     
/home/chris/Pictures/LOCAL_RAW/160_PANA/P1606024.RW2: data corrupted at 598016                                                                                
/home/chris/Pictures/LOCAL_RAW/160_PANA/P1606025.RW2: data corrupted at 536064                                                                                
   355.6261 [libraw_open] extensions whitelist: `cr3 rw2'                                                                                                     
   355.6289 [libraw_open] extensions whitelist: `cr3 rw2'                                                                                                     
/home/chris/Pictures/LOCAL_RAW/160_PANA/P1606021.RW2: data corrupted at 607232                                                                                
/home/chris/Pictures/LOCAL_RAW/160_PANA/P1606023.RW2: data corrupted at 952320                                                                                
   355.6312 [libraw_open] extensions whitelist: `cr3 rw2'                                                                                                     
/home/chris/Pictures/LOCAL_RAW/160_PANA/P1606022.RW2: data corrupted at 628736                                                                                
   355.6530 [libraw_open] extensions whitelist: `cr3 rw2'                                                                                                     
/home/chris/Pictures/LOCAL_RAW/160_PANA/P1606019.RW2: data corrupted at 569344                                                                                
   355.6590 [libraw_open] extensions whitelist: `cr3 rw2'                                                                                                     
   355.6599 [libraw_open] extensions whitelist: `cr3 rw2'    
/home/chris/Pictures/LOCAL_RAW/160_PANA/P1606020.RW2: data corrupted at 528896
/home/chris/Pictures/LOCAL_RAW/160_PANA/P1606018.RW2: data corrupted at 583680
   356.3565 [libraw_open] extensions whitelist: `cr3 rw2'
/home/chris/Pictures/LOCAL_RAW/160_PANA/P1606017.RW2: data corrupted at 598528
   356.6646 [libraw_open] extensions whitelist: `cr3 rw2'
/home/chris/Pictures/LOCAL_RAW/160_PANA/P1606016.RW2: data corrupted at 584192
```

This results in corrupted images:

![image](https://github.com/user-attachments/assets/50dab4a7-011b-4857-b6fc-ff2b921c35a9)

Note that the raw files on disk are perfectly fine, and downgrading via the command below resolves the issue:
```
sudo flatpak update --commit=c228640ec5e8ea6aafeca6eb95a85117d03724c98064b5c744fefabcdd48df6f org.darktable.Darktable
```

(For anyone coming here due to experiencing the issue, note that the thumbnails will not automatically regenerate after downgrading, so they will appear to still be corrupted until it is regenerated, e.g. by making an edit to the photo.)

The raw files are too large to attach here, so I've uploaded one to Google Drive - you can grab it from [here](https://drive.google.com/file/d/1FvP8epB9MUPEcH8WigYu6lwCND3Wxaci/view?usp=sharing).

**Comment by ChristopherRogers1991** [comment]
This might be more nuanced - it doesn't appear to be every photo, and doesn't always behave the same way to for the same photo. Probably safe to ignore this (or even close it) until I have more info.

**Comment by hfiguiere** [comment]
this file works fine here 

![image](https://github.com/user-attachments/assets/ca559783-8463-4f21-96fe-716b64cf3b7b)

**Comment by ChristopherRogers1991** [comment]
Thanks for looking into this - the behavior is very odd, but does not appear related to the flatpak. It first occurred after an upgrade, and downgrading _seemed_ to fix it. But then it happened on the older version, and with the AppImage. I was about to file a bug on the main darktable repo, but the very last section asked if it occurred with a clean config dir - starting with a clean directory seems to have resolved it (at least for the AppImage, presumably for the flatpak as well).

Closing this out. Apologies for the noise.
