### ISSUE TITLE
Update app ID

### ISSUE THREAD

**Issue by albertescanes** [flathub/org.darktable.Darktable#134]
Upstream app ID is `org.darktable.darktable` rather than `org.darktable.Darktable`.

https://github.com/darktable-org/darktable/blob/d9e1adf584a070bf65af7298c6f43812497b5270/data/org.darktable.darktable.appdata.xml.in#L5

I don't know if it's worth going through the renaming process though.

**Comment by paperdigits** [comment]
darktable is deliberately spelled with a lower case d. I don't think we'll be renaming.

**Comment by hfiguiere** [comment]
This was done before the appstream upstream got changed to have an app-id.

There is no reason to rename.
