### ISSUE TITLE
Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.darktable.Darktable#2]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

**Comment by matze** [comment]
Hmm, how is this done/specified?

**Comment by TingPing** [comment]
https://github.com/flathub/com.discordapp.Discord/blob/master/com.discordapp.Discord.appdata.xml#L11-L20

**Comment by julianrichen** [comment]
This was fixed upstream with:
darktable-org/darktable@dbba8bbb3aa7b740a4e0e3c8576394ecbeb977ac
darktable-org/darktable@fdc370cc6e0251d2500f8ffcfdea9da2a40aa342

So it can be closed.
