### ISSUE TITLE
how to execute the darktable binaries (darktable-cli, darktable-generate-cache, etc)

### ISSUE THREAD

**Issue by bornf** [flathub/org.darktable.Darktable#20]
is there a way to execute the binaries of darktable beside the main one?

**Comment by jurf** [comment]
Yes.

```
flatpak run --command=darktable-cli org.darktable.Darktable
```

Or even `flatpak run --command=sh org.darktable.Darktable` and do whatever you want inside.

**Comment by bornf** [comment]
it's so easy :-)
thanks
