### ISSUE TITLE
The thumbnail image is not in JPEG format, but DT was built without GraphicsMagick. Please rebuild...

### ISSUE THREAD

**Issue by bornf** [flathub/org.darktable.Darktable#21]
executing darktable-generate-cache binary produces this log on some images...

```
[dt_imageio_large_thumbnail] error: The thumbnail image is not in JPEG format, but DT was built without GraphicsMagick. Please rebuild DT with GraphicsMagick support enabled.
[dt_imageio_large_thumbnail] error: Not a supported thumbnail image format or broken thumbnail: image/tiff
```

mhh, obviously darktable was built without GraphicsMagick support...

**Comment by hfiguiere** [comment]
Which kind of image if you know? This would allow to validate the fix.

Thanks.

**Comment by eszlari** [comment]
> Which kind of image if you know? This would allow to validate the fix.

Look at the quoted output (scroll to the right): `image/tiff`

**Comment by hfiguiere** [comment]
That's the thumbnail format. But which file does have that?

**Comment by hfiguiere** [comment]
The latest flaptak build has GraphicsMagick. Please let us know if that fixes your issues.
