### ISSUE TITLE
Map mode is missing

### ISSUE THREAD

**Issue by garrett** [flathub/org.darktable.Darktable#22]
I'm on Fedora 29 beta (and also on F28 release) and have noticed that the Flatpak version of darktable does not have the "map" mode for seeing geo related information & geotagging.

The standard F28 & F29 versions have this, but the Flatpak build does not.

Perhaps there's some dependency not pulled in during build time?

**Comment by paperdigits** [comment]
I think it has to do with missing optional dependencies, such as `libosmgpsmap-1.0-dev`

**Comment by paperdigits** [comment]
List of optional dependencies: `libgphoto2-dev libsoup2.4-dev libopenexr-dev libwebp-dev libflickcurl-dev libopenjp2-7-dev libsecret-1-dev libgraphicsmagick1-dev libcolord-dev libcolord-gtk-dev libcups2-dev libsdl1.2-dev libsdl-image1.2-dev libgl1-mesa-dev libosmgpsmap-1.0-dev libopenjp2-7-dev llvm-3.9 clang-3.9 python3-jsonschema`

**Comment by hfiguiere** [comment]
I have a PR that will fix both the map issue and 2.6.0 release.

**Comment by matze** [comment]
Thanks, it's merged.
