### ISSUE TITLE
Darktable does not find my camera

### ISSUE THREAD

**Issue by w-wagner** [flathub/org.darktable.Darktable#26]
I am running debian stable and used this version to get the recent features of darktable.
When I am using the version 2.4.4 darktable does not find my camera.
If I am running the debian release 2.2.1. the camera is found and the import works as expected.

My current workaround is to import in the old version and do the processing in the new version.
I guess something is broken...

**Comment by hfiguiere** [comment]
This is issue #4 and PR #24.

**Comment by hfiguiere** [comment]
The PR hasn't been merged, which mean it is unlikely to be in the currently available build.

Just that this issue is a duplicate of the other.
