### ISSUE TITLE
darktable 2.6.0 flatpak unable to view/edit .exr files

### ISSUE THREAD

**Issue by DaveBlack** [flathub/org.darktable.Darktable#27]
**Describe the bug**
Unable to view .exr files (no preview), and unable to edit

**Non-working version**
darktable 2.6.0 flatpak

**Working versions**
darktable 2.6.0 PPA 18.04 (ppa:pmjdebruijn/darktable-release)
darktable 2.6.0 for Windows

**To Reproduce**
1. Using GIMP 2.10.8, or Blender 2.79 save an image as a .exr file
2. Open .exr with darktable

**Expected behavior**
.exr should present a preview, and be editable

**Operating Systems tested**
Linux Mint 19.1 64-bit Cinnamon Edition
Windows 7 64-bit

Forgot to say thank you, the flatpak version is greatly appreciated!

**Comment by hfiguiere** [comment]
It is likely the dependency is missing.

**Comment by hfiguiere** [comment]
The latest flatpak has libexr support.

**Comment by DaveBlack** [comment]
Thank you hfiguiere for fixing this, your work is greatly appreciated!
