### ISSUE TITLE
Where is the exiv2 user file located?

### ISSUE THREAD

**Issue by paperdigits** [flathub/org.darktable.Darktable#32]
I'd like to make some custom adjustments to the lens list exiv2 uses. This can be done with exiv2 from the package manager by writing to `~/.exiv2`, but the same file for the flatpak is not effective.

**Comment by matze** [comment]
This is not related to the Darktable Flatpak: https://github.com/flatpak/flatpak/issues/1214.

**Comment by paperdigits** [comment]
It seems that exiv2 is not present or not on the $PATH. When I run a bash shell in the darktable environment, it doesn't return anything:

```
m@t .var % flatpak run --command=bash org.darktable.Darktable 
m@t:~/.var$ exiv2 -vVg config_path
bash: exiv2: command not found

**Comment by hfiguiere** [comment]
The `exiv2` command isn't in the flatpak.

**Comment by paperdigits** [comment]
@hfiguiere no it is not. I may build exiv2 in the flatpak to see if I can get this working. Otherwise, I'm open to suggestion on what to do!

**Comment by hfiguiere** [comment]
You probably don't need to go that far. Just use the `exiv2` packaged in your distribution to write to `.var/app/org.darktable.Darktable/.exiv2` from outside of the flatpak.

**Comment by paperdigits** [comment]
@hfiguiere that location doesn't work for me either.
