### ISSUE TITLE
Grant filesystem access to xdg-run/gvfs

### ISSUE THREAD

**Issue by cjao** [flathub/org.darktable.Darktable#38]
MTP camera devices are automatically mounted under /run/user/$UID/gvfs. To let Darktable import images from such devices, one should grant filesystem access to xdg-run/gvfs (see https://github.com/flatpak/flatpak/issues/2923#issuecomment-496354265).

**Comment by paperdigits** [comment]
From the command line use `--filesystem=xdg-run/gvfs`

**Comment by hfiguiere** [comment]
This is what the PR #39 propose.
