### ISSUE TITLE
Lensfun database version

### ISSUE THREAD

**Issue by richryan51** [flathub/org.darktable.Darktable#40]
I realize this is an ongoing problem. Lensfun updates their database but the Darktable flatpak build is not updated. The Lensfun database was updated to include the RX100M6 (RX100vi) four months ago (April 2019). I tried to put the updated compact-sony.xml file in my local/share/lensfun directory but the Flatpak version does not seem to look there (which seems to make sense). Is it possible to get the Flatpak Darktable to look for external Lensfun updates?

If not possible to get the external links then, is it possible to get an updated Flatpak build with the latest Lensfun database?

**Comment by matze** [comment]
The lensfun files are (usually) located in `/var/lib/flatpak/app/org.darktable.Darktable/current/active/files/share/lensfun/version_2/`, so you might have luck dropping those files there. Looking for external locations is probably too much hassle, so a new release with an updated lensfun database is probably the better option.

**Comment by richryan51** [comment]
Editing the file in that location worked. This issue can be closed from my standpoint, but I'm sure many others would enjoy a build with the latest Lensfun database.
