### ISSUE TITLE
Colord can't load an ICC profile.

### ISSUE THREAD

**Issue by paperdigits** [flathub/org.darktable.Darktable#44]
I've been having problems matching prints to my monitor, even though everything is calibrated. 

It seems that colord, though built into the flatpak, can't actually load a profile:

```
flatpak run --command=darktable-cmstest org.darktable.Darktable 
darktable-cmstest version 2.6.2
this executable was built with colord support enabled
darktable itself was built with colord support enabled

primary CRTC is at CRTC 0
CRTC for screen 0 CRTC 1 has no mode or no output, skipping
CRTC for screen 0 CRTC 2 has no mode or no output, skipping
error connecting to colord

eDP-1   the X atom and colord returned different profiles
        X atom: _ICC_PROFILE (1152 bytes)
                description: Galago Pro
        colord: "(none)"
                description: (file not found)

Better check your system setup
 - some monitors reported different profiles
You may experience inconsistent color rendition between color managed applications
```

**Comment by hfiguiere** [comment]
This probably the same issue as #16

**Comment by paperdigits** [comment]
@hfiguiere when I read #16, it seems to me to be about file system access to a specific place in the filesystem hierarchy. 

This is about colord, which does the color managemnet for darktable being able to load and display a color profile. `colormgr` is not present inside the sandbox, so ICC profiles cannot be loaded. The end result is that the darktable flatpak is not color managed. For my purposes, this make it unusable, as I've calibrated my monitor and my printer, but if darktable isn't using the color profile, then I'm not actually seeing the correct colors on my screen.
