### ISSUE TITLE
Darktable 3.0 availability

### ISSUE THREAD

**Issue by idvoretskyi** [flathub/org.darktable.Darktable#47]
Darktable 3.0 has been released recently (https://github.com/darktable-org/darktable/releases/tag/release-3.0.0), please update the Flatpak application to the latest version of the software.

**Comment by idvoretskyi** [comment]
Ref: https://github.com/flathub/org.darktable.Darktable/pull/48

**Comment by hfiguiere** [comment]
And to summarize it is currently blocked on some issues that are unlikely to be solved quickly.

**Comment by matze** [comment]
Depends on https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/943
