### ISSUE TITLE
Darktable 3.0 Flatpak themes broken

### ISSUE THREAD

**Issue by hcw70** [flathub/org.darktable.Darktable#50]
**Describe the bug**
If changing themes in the 3.0 flatpak version to something other than the default theme, most themes show empty squares instead of the texts, so GUI becomes unusable. 

**To Reproduce**
Go to preferences and change theme to i.e. "darktable-icons-darker".

**Screenshots**
See screenshot

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Ubuntu 19.10 
 - OpenCL activated
 - Which graphics card and driver version: NVidia GTX960M, Version 435.21

![](https://user-images.githubusercontent.com/1888459/74140957-59de4b80-4bf6-11ea-9354-d69b9cf77cb9.png)

**Comment by TingPing** [comment]
Corrupted fontconfig cache perhaps. Can you delete the cache dir for darktable?

**Comment by hfiguiere** [comment]
FWIW It works here on Fedora 31.

**Comment by hcw70** [comment]
> Corrupted fontconfig cache perhaps. Can you delete the cache dir for darktable?

Will try. How do i do this?

**Comment by hcw70** [comment]
Ok, i figured it out:

`flatpak run --command=fc-cache org.darktable.Darktable -f -v
`

based on the hint from https://github.com/flatpak/flatpak/issues/3191 .

Now themes work great!
