### ISSUE TITLE
Can't trash across fs boundary

### ISSUE THREAD

**Issue by Firstyear** [flathub/org.darktable.Darktable#6]
Please see https://github.com/flatpak/flatpak/issues/1253

When trashing items from darktable the error "cannot trash across fs boundary" is recieved. This appears to be related to flatpak of darktable not having the gvfs permission,

It would be great to be able to use trash for darktable properly! Thank you

**Comment by paperdigits** [comment]
You can try `flatpak run --talk-name=org.gtk.vfs --talk-name=org.gtk.vfs.* org.darktable.Darktable` as a work-around.

**Comment by matze** [comment]
@Firstyear please test with the change by @paperdigits and re-open if necessary.

**Comment by paperdigits** [comment]
Cool I hope it works. I think I got the flathub update today.

**Comment by TingPing** [comment]
There is no delay once the build has finished but you can verify with `flatpak remote-info --user flathub org.darktable.Darktable` and see:
```
Date: 2018-01-09 08:00:48 +0000
Subject: Add support to talk to GVFS (620b541f)
```

**Comment by Firstyear** [comment]
This is a good tip @TingPing Thank you! 

Sadly, need to ask you to reopen as this issue still persists with latest darktable update :( 

Suggested workaround of ```flatpak run --talk-name=org.gtk.vfs --talk-name=org.gtk.vfs.\* org.darktable.Darktable ``` Does not work either :( 

```
flatpak info org.darktable.Darktable
Ref: app/org.darktable.Darktable/x86_64/stable
ID: org.darktable.Darktable
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2018-01-09 08:00:48 +0000
Subject: Add support to talk to GVFS (620b541f)
Commit: b837bd5fcaafc3531ddd1c64862723d840a5359d6db4556fe0f2b4780db8fa55
Parent: aee2516b2b6583ebb0bc80877c58eff23f717a3868980c76c04140c471ba6bcf
Location: /var/lib/flatpak/app/org.darktable.Darktable/x86_64/stable/b837bd5fcaafc3531ddd1c64862723d840a5359d6db4556fe0f2b4780db8fa55
Installed size: 24.4 MB
Runtime: org.gnome.Platform/x86_64/3.24
```

**Comment by Firstyear** [comment]
Could this possibly be related to https://github.com/flatpak/flatpak/issues/1278 ???

**Comment by Firstyear** [comment]
Hi. Just a reminder that this issue is still present :(

**Comment by omichalek** [comment]
I am confused - why is this bug still reoccuring? And why does it happen so inconsistently? I ran this program maybe a week ago without any problem...

```
user@machine:~$ flatpak run org.fedoraproject.MediaWriter
bwrap: Can't make symlink at /var/run: File exists
user@machine:~$ ls -al /var/run
lrwxrwxrwx 1 root root 4 dub 24  2018 /var/run -> /run
user@machine:~$ flatpak --version
Flatpak 1.2.4
user@machine:~$ uname -a
Linux machine 5.0.5-1-default #1 SMP Wed Mar 27 11:22:35 UTC 2019 (0fb0b14) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by SuborbitalPigeon** [comment]
> edit: sorry, this was probably not the best place to post it

Thank you for spamming us with this irrelevant nonsense.

**Comment by jurf** [comment]
@SuborbitalPigeon he already apologised. Adding sarcastic comments doesn’t help anything.
