### ISSUE TITLE
avif export not working

### ISSUE THREAD

**Issue by nilsholle** [flathub/org.darktable.Darktable#64]
**Describe the bug**
The following error is produced when trying to export to an avif file using the latest Flatpak from Flathub:

[dt_exif_xmp_attach_export] /var/home/.../darktable_exported/IMG_8021_01.avif: caught exiv2 exception '/var/home/.../darktable_exported/IMG_8021_01.avif: Failed to open the data source: Datei oder Verzeichnis nicht gefunden (errno = 2)'
[imageio_storage_disk] could not export to file: `/var/home/.../darktable_exported/IMG_8021_01.avif'!

JPEG export works perfectly fine.

**To Reproduce**
1. Select image
2. Try to export to .avif

**Expected behavior**
Export should work.

**Platform**
 - Darktable Version: 3.2.1 (Flatpak)
 - OS: Fedora Silverblue 32

**Comment by hfiguiere** [comment]
I wonder if avif shouldn't be built before exiv2.

**Comment by hfiguiere** [comment]
```
[dt_exif_xmp_attach_export] /home/hub/Pictures/20181217/darktable_exported/DSCF3063.avif: caught exiv2 exception '/home/hub/Pictures/20181217/darktable_exported/DSCF3063.avif: The file contains data of an unknown image type'
```

This looks better.

**Comment by hfiguiere** [comment]
btw, exporting take and LOOONNNNGGGG time and make my system thrash (I have 16GB)

**Comment by hfiguiere** [comment]
This will be in the next update of the flatpak (give it a few hours to appear).

Thanks !
