### ISSUE TITLE
Lua scripts installer requires git

### ISSUE THREAD

**Issue by SuborbitalPigeon** [flathub/org.darktable.Darktable#71]
With version 3.4.0 of Darktable, a notification appears asking the user to install lua scripts. However, this fails due to git being missing.

**Comment by hfiguiere** [comment]
See also https://github.com/flathub/org.darktable.Darktable/issues/66#issuecomment-751124820

**Comment by SuborbitalPigeon** [comment]
Apologies for not noticing the other bug before filing this one.
