### ISSUE TITLE
Doesn't show selected pictures

### ISSUE THREAD

**Issue by mippo9** [flathub/org.darktable.Darktable#73]
In both the Lighttable and Darkroom views, doesn't show the pictures selected.
The same as above for color selectors, grading stars and pick flag.
By the way, it seems it still considering them, even if not shown.
Darktable 3.4.0 from Flathub

My system:
Operating System: KDE neon 5.20
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.77.0
Qt Version: 5.15.2
Kernel Version: 5.4.0-58-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
Memory: 7,5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by paperdigits** [comment]
Can you explain a bit more what you mean by "doesn't show the selected photo"?

Steps to reproduce would be good.

**Comment by hfiguiere** [comment]
And a screenshot

**Comment by mippo9** [comment]
Mica,
thanks for very quick answer.
find attached a screenshot of Light table from release 3.2.1, where you can
see the 2nd and the 4th pictures selected.
The mouse is on the 4th and the screen shows the one-star grading, for it.
Now, this doesn't happen in 3.4.0, the light gray border around the
selected pictures doesn't appear, the same for the grading stars.
The stars appear white, empty, always.
[image: image.png]

Il giorno mar 29 dic 2020 alle ore 00:49 Mica <notifications@github.com> ha
scritto:

**Comment by paperdigits** [comment]
I don't see a screenshot.

**Comment by hfiguiere** [comment]
Attachment via email don't work. Please attach it through the web interface.

**Comment by hfiguiere** [comment]
It looks like this here:

![image](https://user-images.githubusercontent.com/114441/103251501-de3cd880-4946-11eb-8ab3-507e78d39279.png)

Standard GNOME on Fedora 33.

**Comment by mippo9** [comment]
send again, it's a 600k png ...

Il giorno mar 29 dic 2020 alle ore 01:33 Mica <notifications@github.com> ha
scritto:

**Comment by hfiguiere** [comment]
Still no screenshot.

**Comment by mippo9** [comment]
converted into pdf ...

Il giorno mar 29 dic 2020 alle ore 02:38 Hubert Figuière <
notifications@github.com> ha scritto:

**Comment by mippo9** [comment]
I'm sorry, i cannot succeed with this attachment.
Anyway, the question is very simple, I cannot see the light-gray border, neither the stars, if settled.
This happens in both the views, in Lighttable and in Darkroom
the picture attached above by hfiguiere, is correct, with its gray border.

**Comment by hfiguiere** [comment]
You can attach with the web interface.

Without screenshot I can't see what the problem is.

**Comment by mippo9** [comment]
> You can attach with the web interface.
> 
> Without screenshot I can't see what the problem is.

[Screenshot_20201229_010835.pdf](https://github.com/flathub/org.darktable.Darktable/files/5749378/Screenshot_20201229_010835.pdf)
this is from 3.2.1, with 2 selected pictures, the 2nd and the 4th

![Screenshot_20201229_032825](https://user-images.githubusercontent.com/76710389/103254542-039d0700-4986-11eb-813c-a37889ba9505.png)
and this is from 3.4.0, I can click everywhere, but nothing happen, no possible to select any pictures.

**Comment by hfiguiere** [comment]
There is seems to be two things:

- something is changing the theme of Darktable and that's probably the source of the problem.
- There seems to be also graphics artifacts.

**Comment by mippo9** [comment]
I have installed 3.4.0 a couple of days ago, just tested something, maybe also changed the teme.
Then after having had the problem, I have uninstalled it and then installed again, but now without change anything.
But the problem persists.

**Comment by hfiguiere** [comment]
uninstalling it doesn't wipe the settings.

**Comment by mippo9** [comment]
if I remember well, I never seen the picture selection possibility, from immediately after installing.
is there a config file I can remove ?
after that, I need a simply restart or I need a unistall /reinstall ?

**Comment by mippo9** [comment]
I have other 2 release, I don't want to remove ...
3.0.1 and 3.2.1
hope their settings doesn't affect the new 3.4.0

**Comment by hfiguiere** [comment]
All the settings for the flatpak version are in 
`~/.var/app/org.darktable.Darktable/config/darktable`

But there don't seem to be versioning so it might already be too late to run the old versions are flatpak.

**Comment by mippo9** [comment]
This is its content:
![Screenshot_20201229_113322](https://user-images.githubusercontent.com/76710389/103277631-cb1f1c80-49c9-11eb-9c4c-090eac6e0f72.png)

**Comment by hfiguiere** [comment]
tbf I have no idea which is what, but I think `darktablerc` and `user.css` would be the two I go for. (rename them as backup)

**Comment by paperdigits** [comment]
Note that settings files and databases are generally not considered backward compatible and the darktable team makes no effort to ensure backward compatibility with its config files. 

I'd rename the files one at a time to `<filename>.old` and launch darktable after each change.

**Comment by paperdigits** [comment]
Please request this to reopen if need be.
