### ISSUE TITLE
White balance problem with RW2 files in flatpak 3.6.1

### ISSUE THREAD

**Issue by rothbert** [flathub/org.darktable.Darktable#80]
I've using flatpak darktable on linux mint 19.x (currently 19.3) since ver 2.6.3. Don't recall having this problem before, in fact don't recall it happening before 3.6.1. Seems to affect some images more than others. RW2 files are from a Panasonic GH5.

Problem: White balance is out on those raw files - seems to be a magenta cast over the whole of the image, possibly  more in shadows. Some images I've been able to deal with this using the white balance module (color calibration module doesn't seem to help) - tweaking channels etc.

Other images, no dice. No matter what I do with the white balance (or any other tools) can't get the image looking right.

Input color profile is 'standard color matrix', working profile is linear Rec2020 RGB - both defaults, changing those doesn't seem useful.

Making comparison with JPGs of the same image.

Loaded the OBS version for Ubuntu 18.04 - 3.4.1.1~git0.3641 and the RW2 files are fine, no cast.

Any suggestions welcome.

Thanks for your work on the flatpak, super handy option.

**Comment by paperdigits** [comment]
Hi,

The issue is that Panasonic doesn't use a fixed value for black point. This is an issue in 3.6.1. See https://discuss.pixls.us/t/panasonic-g9-and-darkable-issues-white-balance-colours-are-off/27438

This is not a flatpak issue.

**Comment by rothbert** [comment]
Ah right - I realized I couldn't check with another version of 3.6.1.
Thanks for that link - going to have good read through now.
