### ISSUE TITLE
Why does it need to acces to all system files?

### ISSUE THREAD

**Issue by ghost** [flathub/org.darktable.Darktable#84]
It is very, **very** excessive permission for a photo editor. Please fix this asap since the application run just fine without that permission anyway. Things like this destroys the whole purpose of flatpak.

**Comment by paperdigits** [comment]
I think a whole lot of people have their photos in nonstandard places, like a nas or external disk.

If you don't like the defaults, change them to what you'd like them to be, that's the way flatpak is designed.
