### ISSUE TITLE
Permission filesystem=host not working

### ISSUE THREAD

**Issue by OldNick** [flathub/org.darktable.Darktable#87]
Darktable flatpak is installed on chromebook linux.
To access my images, I need to go `/mnt/chromeos/external/...` when I try to, using the file picker-dialogue, clicking "other locations" the "computer" icon is greyed out and unresponsive.
I am, in fact, firmly stuck in the `/home/user` directory.
I have verified that Darktable has the necessary permissions, tried, using Flatseal, to point the app explicitly at the directory I want, all to know avail.
I'm leaving the app installed in the hope there is a solution to this...

**Comment by hfiguiere** [comment]
`/mnt/chromeos/external` this is a non standard path.

If only ChromeOS followed standards.

**Comment by OldNick** [comment]
Perhaps it isn't conventional but Rawtherapee, Freesync and Geeqie (all installed as flatpak apps) DO work - after tweaking the overrides. Chrome Linux is essentially a VM with pathways open to shared directories.

On April 8, 2022 3:04:26 PM GMT+02:00, "Hubert Figuière" ***@***.***> wrote:
>`/mnt/chromeos/external` this is a non standard path.
>
>If only ChromeOS followed standards.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/flathub/org.darktable.Darktable/issues/87#issuecomment-1092837746
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by paperdigits** [comment]
If you've used flatseal to adjust the permissions to the correct path, I'm not sure what else we can do.

**Comment by OldNick** [comment]
Maybe find out why? 
It's the only flatpak that's misbehaved in this way. I've tried quite a few - a lot have bugs of various kinds, but none this particular one.

On April 8, 2022 9:45:07 PM GMT+02:00, Mica ***@***.***> wrote:
>If you've used flatseal to adjust the permissions to the correct path, I'm not sure what else we can do.
>
>
>
>On April 8, 2022 11:37:13 AM PDT, OldNick ***@***.***> wrote:
>
>>Perhaps it isn't conventional but Rawtherapee, Freesync and Geeqie (all installed as flatpak apps) DO work - after tweaking the overrides. Chrome Linux is essentially a VM with pathways open to shared directories.
>
>>
>
>>
>
>>
>
>>On April 8, 2022 3:04:26 PM GMT+02:00, "Hubert Figuière" ***@***.***> wrote:
>
>>
>
>>>`/mnt/chromeos/external` this is a non standard path.
>
>>
>
>>>
>
>>
>
>>>If only ChromeOS followed standards.
>
>>
>
>>>
>
>>
>
>>>-- >
>
>>>Reply to this email directly or view it on GitHub:
>
>>
>
>>>https://github.com/flathub/org.darktable.Darktable/issues/87#issuecomment-1092837746
>
>>
>
>>>You are receiving this because you authored the thread.
>
>>
>
>>>
>
>>
>
>>>Message ID: ***@***.***>
>
>>
>
>>-- >
>
>>Sent from my Android device with K-9 Mail. Please excuse my brevity.
>
>>
>
>>
>
>>
>
>>-- >
>
>>Reply to this email directly or view it on GitHub:
>
>>
>
>>https://github.com/flathub/org.darktable.Darktable/issues/87#issuecomment-1093196912
>
>>
>
>>You are receiving this because you are subscribed to this thread.
>
>>
>
>>
>
>>
>
>>Message ID: ***@***.***>
>
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/flathub/org.darktable.Darktable/issues/87#issuecomment-1093296642
>
>You are receiving this because you authored the thread.
>
>
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by paperdigits** [comment]
I don't own a Chromebook and I don't want one. You have the issue and you can reproduce it. If you can tell us what is wrong we can fix it, but if you can't you'll have to find someone who can.

**Comment by OldNick** [comment]
Thank you for the reply
It has cured me from ever wanting to use flatpaks

**Comment by OldNick** [comment]
The solution is to add permissions for the /mnt directory
