### ISSUE TITLE
How to use darktable-cli?

### ISSUE THREAD

**Issue by hubslave** [flathub/org.darktable.Darktable#9]
Hello friends,

Darktable application comes with a utility called darktable-cli - a command line batch utility for processing photos from terminal. Is it possible to use this utility when I have Darktable installed as flatpak? If yes how can I use it?

Thank you very much for your time and have a nice day :)

**Comment by BellaCoola** [comment]
@TingPing answered my question, so I post it also here, if anybody else would be looking for this:

`flatpak run --command=darktable-cli org.darktable.Darktable --arguments-go-here`

**Comment by hubslave** [comment]
@TingPing answered my question, so I post it also here, if anybody else would be looking for this:

`flatpak run --command=darktable-cli org.darktable.Darktable --arguments-go-here`

**Comment by jurf** [comment]
Or, in a more logical order:
```
flatpak run org.darktable.Darktable --command=darktable-cli --arguments-go-here
```
