### ISSUE TITLE
Flatpak update to 3.8.1 failes

### ISSUE THREAD

**Issue by dmoltisanti** [flathub/org.darktable.Darktable#90]
Hi and thanks for maintaining this! When I try to update darktable from 3.8 to 3.8.1 I get a checksum error:

```bash
Error: While pulling app/org.darktable.Darktable/x86_64/stable from remote flathub: 
opcode close: Corrupted file object; checksum 
expected='2567ce1eb55602a82256929dfa88d862e4788e0b616ae0096733ae2ad80c35a6'
actual='a54e7121a6444259abc41f60bbd0573598d0f8718b474691810c54a1973002cb'
```
Is this happening only to me? Could this be happening because I modified myself a file inside the `lensfun` folder (to add a lens configuration manually)?

Thanks in advance

**Comment by paperdigits** [comment]
I haven't heard any other reports of this, can you remove your modifications, use flatpak to rollback to 3.8.0, make sure you're on a stable network, and try again?

If that doesn't work, maybe an fscheck of your disk.

**Comment by hfiguiere** [comment]
1. try `flatpak repair`
2. if that doesn't work, uninstall and reinstall the app
3. never ever take the advice to change files inside the sandbox. Any advice like that is wrong

**Comment by dmoltisanti** [comment]
Thanks, reinstalling it worked. I didn't follow anyone's advice, I just ventured down the wrong path myself :D 

What would the right way to add a lens manually to lensfun database then? I have lensfun installed via `dnf`, but Dartkable installs its own copy and looks only inside its sandboxed database. That's why I edited the file inside the sandbox.

Thanks again!

**Comment by paperdigits** [comment]
I'm not sure we have figures out where user level lensfun files go. The flatpak pulls a very recent version of the lensfun db, so getting your lens profile into lensfun is what is generally recommended.

Since the flatpak is sand boxed, the usual user location isn't picked up. It'd be nice to figure it out though.
