### ISSUE TITLE
Darktable 4.0 released

### ISSUE THREAD

**Issue by 0b11001111** [flathub/org.darktable.Darktable#91]
Title says everything. Here's the corresponding blog post: https://www.darktable.org/2022/07/darktable-4.0/

**Comment by paperdigits** [comment]
Why not try and make a PR yourself? :)

**Comment by 0b11001111** [comment]
Never done that :P but I can try if you give me a sketch of things to do :)

**Comment by 0b11001111** [comment]
Okay, I started playing with it. There was a broken link I fixed and now it's building. My plan is to upgrade darktable and all dependencies. Is there anything else that has to be done before opening the PR?
