### ISSUE TITLE
OpenCL-Nvidia crashing

### ISSUE THREAD

**Issue by marcsitkin** [flathub/org.darktable.Darktable#93]
Using flapak of Darktable 4.0, Nvidia Geforce 1060 TI card, getting crashes while scrolling or exporting in lightable
`System:    Host: marcs-HP-ENVY-Desktop-795-00xx Kernel: 5.15.0-41-generic x86_64 bits: 64 Desktop: Gnome 3.38.4 
           Distro: Zorin OS 16.1 
Machine:   Type: Desktop System: HP product: HP ENVY Desktop 795-00xx v: N/A serial: 8CG8324KS3 
           Mobo: HP model: 844C v: 00 serial: PGSWD0D0GB4A20 UEFI: AMI v: F.40 date: 11/21/2019 
CPU:       Topology: 6-Core model: Intel Core i7-8700 bits: 64 type: MT MCP L2 cache: 12.0 MiB 
           Speed: 921 MHz min/max: 800/4600 MHz Core speeds (MHz): 1: 1390 2: 938 3: 951 4: 999 5: 957 6: 900 7: 2003 
           8: 900 9: 929 10: 1048 11: 900 12: 900 
Graphics:  Device-1: NVIDIA GP106 [GeForce GTX 1060 3GB] driver: nvidia v: 510.73.05 
           Display: server: X.Org 1.20.13 driver: nvidia unloaded: fbdev,modesetting,nouveau,vesa 
           resolution: 2560x1600~60Hz 
           OpenGL: renderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2 v: 4.6.0 NVIDIA 510.73.05 
Audio:     Device-1: Intel Cannon Lake PCH cAVS driver: snd_hda_intel 
           Device-2: NVIDIA GP106 High Definition Audio driver: snd_hda_intel 
           Device-3: Sunplus Innovation type: USB driver: snd-usb-audio,uvcvideo 
           Sound Server: ALSA v: k5.15.0-41-generic 
Network:   Device-1: Realtek RTL8821CE 802.11ac PCIe Wireless Network Adapter driver: rtw_8821ce 
           IF: wlp60s0 state: down mac: 90:32:4b:3f:87:7b 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           IF: enp61s0 state: up speed: 1000 Mbps duplex: full mac: 10:62:e5:11:97:25 
Drives:    Local Storage: total: 10.25 TiB used: 5.86 TiB (57.1%) 
           ID-1: /dev/nvme0n1 vendor: A-Data model: SX8200PNP size: 476.94 GiB 
           ID-2: /dev/nvme1n1 vendor: Seagate model: XPG GAMMIX S50 Lite size: 953.87 GiB 
           ID-3: /dev/sda vendor: Micron model: MTFDDAV256TBN-1AR1ZABHA size: 238.47 GiB 
           ID-4: /dev/sdb vendor: Crucial model: CT1000MX500SSD1 size: 931.51 GiB 
           ID-5: /dev/sdc vendor: Western Digital model: WD30EZRX-00SPEB0 size: 2.73 TiB 
           ID-6: /dev/sdd type: USB vendor: Western Digital model: WD40EZRZ-22GXCB0 size: 3.64 TiB 
           ID-7: /dev/sde type: USB vendor: Western Digital model: WD15EARS-00MVWB0 size: 1.36 TiB 
           ID-8: /dev/sdf type: USB vendor: Hitachi model: HDT721010SLA360 size: 931.51 GiB 
Partition: ID-1: / size: 467.89 GiB used: 208.22 GiB (44.5%) fs: ext4 dev: /dev/nvme0n1p2 
Sensors:   System Temperatures: cpu: 71.0 C mobo: 27.8 C gpu: nvidia temp: 48 C 
           Fan Speeds (RPM): N/A gpu: nvidia fan: 0% 
Info:      Processes: 399 Uptime: 47m Memory: 31.22 GiB used: 7.64 GiB (24.5%) Shell: bash inxi: 3.0.38 
`
NOT having opencl issues with a compiled version of R&darktable. Behavior started recently, after an Nvidia update or two.

**Comment by paperdigits** [comment]
Can you (1)/remove the openCL kernels and let darktable regenerate them, if that doesn't prevent the crash, then (2) disable openCL and see if that solves the problem. If that does solve the problem, then you'll need to rollback the flatpak version of the nvidia driver. 

Note there is not much we can do about buggy openCL drivers.

**Comment by marcsitkin** [comment]
Hi Mica

Disabling opencl works.

I don't know enough to remove, rebuild the kernel driver's.

I'll probably hang in to see if an Nvidia update fixes it.

I'm also planning to compile dt once the point release is published.

Thanks for your help, take care.
